(()=>{"use strict";
const SESSION_KEY="absensi_session_v4", PASSWORD_OVERRIDE_KEY="absensi_password_override_v1", CLASSES=["X TITL","X TKJ","X TKR","X TP","XI TITL","XI TKJ","XI TKR","XI TP","XII TITL","XII TKJ","XII TKR.1","XII TKR.2","XII TP"];
const $=id=>document.getElementById(id);
function fillClasses(){const el=$("className");if(!el)return;CLASSES.forEach(c=>{const o=document.createElement("option");o.value=c;o.textContent=c;el.appendChild(o)});}
async function sha256(value){const bytes=new TextEncoder().encode(value);const hash=await crypto.subtle.digest("SHA-256",bytes);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function getGuruData(){try{const r=await fetch("data_guru.json",{cache:"no-store"});if(r.ok)return await r.json()}catch{}return {}}
async function getExpectedPasswordHash(){const override=localStorage.getItem(PASSWORD_OVERRIDE_KEY);if(override)return override;const d=await getGuruData();return d.password_sha256||d.password_hash||await sha256("2334")}
async function getRecoveryHash(){const d=await getGuruData();return d.recovery_code_sha256||""}
async function login(e){e.preventDefault();const username=$("username").value.trim(),password=$("password").value,className=$("className").value,error=$("error");error.classList.add("hidden");if(!username||!password||!className){error.textContent="Username, password, dan kelas wajib diisi.";error.classList.remove("hidden");return}const hash=await sha256(password),expected=await getExpectedPasswordHash();if(hash!==expected){error.textContent="Password guru salah.";error.classList.remove("hidden");return}sessionStorage.setItem(SESSION_KEY,JSON.stringify({role:"guru",username,className,loginAt:new Date().toISOString()}));location.href="absensi_digital.html"}
function clearForm(){$("username").value="";$('password').value="";$('error').classList.add("hidden");$('username').focus()}
function openReset(){["recoveryCode","newPassword","confirmPassword"].forEach(id=>$(id).value="");$("resetError").classList.add("hidden");$("resetSuccess").classList.add("hidden");$("resetModal").classList.remove("hidden");$("recoveryCode").focus()}
function closeReset(){$("resetModal").classList.add("hidden")}
async function resetPassword(){const code=$("recoveryCode").value,newPassword=$("newPassword").value,confirm=$("confirmPassword").value,error=$("resetError"),success=$("resetSuccess");error.classList.add("hidden");success.classList.add("hidden");if(!code||!newPassword||!confirm){error.textContent="Semua kolom pemulihan wajib diisi.";error.classList.remove("hidden");return}if(newPassword.length<4){error.textContent="Password baru minimal 4 karakter.";error.classList.remove("hidden");return}if(newPassword!==confirm){error.textContent="Konfirmasi password tidak sama.";error.classList.remove("hidden");return}const recoveryHash=await getRecoveryHash();if(!recoveryHash||await sha256(code)!==recoveryHash){error.textContent="Kode pemulihan salah.";error.classList.remove("hidden");return}localStorage.setItem(PASSWORD_OVERRIDE_KEY,await sha256(newPassword));success.textContent="Password berhasil diubah. Silakan tutup jendela ini dan login dengan password baru.";success.classList.remove("hidden");$("password").value="";}
fillClasses();$("loginForm").addEventListener("submit",login);$("cancel").addEventListener("click",clearForm);$("forgotPassword").addEventListener("click",e=>{e.preventDefault();openReset()});$("closeReset").addEventListener("click",closeReset);$("saveNewPassword").addEventListener("click",resetPassword);$("resetModal").addEventListener("click",e=>{if(e.target===$("resetModal"))closeReset()});
})();
